- name: Hugo setup
  uses: peaceiris/actions-hugo@v2.4.5
  with:
    # The Hugo version to download (if necessary) and use. Example: 0.58.2
    hugo-version: # optional, default is latest
    # Download (if necessary) and use Hugo extended version. Example: true
    extended: # optional, default is false
